language: go
sudo: required

go:
    - 1.7
    - tip

env:
    - COVERALLS_TOKEN=3NUr5Z9zvjIoGRlKi6WIA3Q9em3x22rZp

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/golang/lint/golint
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/01org/ciao/test-cases
  - go get github.com/opencontainers/runc/libcontainer/configs

install:
  - mkdir -p $HOME/build
  - pushd $HOME/build
  - git clone https://github.com/containernetworking/cni.git
  - cd cni
  - ./build
  - sudo mkdir -p /tmp/cni/bin
  - sudo cp ./bin/bridge /tmp/cni/bin/cni-bridge
  - sudo cp ./bin/loopback /tmp/cni/bin/loopback
  - sudo cp ./bin/host-local /tmp/cni/bin/host-local
  - popd
  - mkdir -p $HOME/build_hook
  - pushd $HOME/build_hook
  - sudo mkdir -p /tmp/bin
  - go build -o hook $GOPATH/src/github.com/containers/virtcontainers/hook/mock/hook.go
  - sudo cp hook /tmp/bin/
  - popd
  - sudo mkdir -p /etc/cni/net.d
  - sudo cp $GOPATH/src/github.com/containers/virtcontainers/test/cni/10-mynet.conf /etc/cni/net.d/
  - sudo cp $GOPATH/src/github.com/containers/virtcontainers/test/cni/99-loopback.conf /etc/cni/net.d/
  - sudo mkdir -p /opt/cni/bin
  - sudo cp /tmp/cni/bin/cni-bridge /opt/cni/bin/
  - sudo cp /tmp/cni/bin/loopback /opt/cni/bin/
  - sudo cp /tmp/cni/bin/host-local /opt/cni/bin/
  - go get -t -v ./...

script:
   - go env
   - go list ./... | xargs -t misspell
   - go list ./... | xargs -t go vet
   - if [[ "$TRAVIS_GO_VERSION" != "tip" ]] ; then go list ./... | xargs -tL 1 golint -set_exit_status ; fi
   - go list ./... | xargs go list -f '{{.Dir}}/*.go' | xargs -I % bash -c "misspell -error %"
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs gocyclo -over 15
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs -L 1 ineffassign
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs gofmt -s -l | wc -l | xargs -I % bash -c "test % -eq 0"
   - go build ./...
   - export GOROOT=`go env GOROOT` && sudo -E PATH=$PATH:$GOROOT/bin:/tmp/cni/bin $GOPATH/bin/test-cases -v -timeout 9 -short -coverprofile /tmp/cover.out github.com/containers/virtcontainers/...

after_success:
   - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=/tmp/cover.out
