language: go
sudo: required

go:
    - 1.7
    - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover
  - go get github.com/fzipp/gocyclo
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/golang/lint/golint
  - go get github.com/client9/misspell/cmd/misspell

script:
   - go env
   - go list ./... | xargs -t misspell
   - go list ./... | xargs -t go vet
   - if [[ "$TRAVIS_GO_VERSION" != "tip" ]] ; then go list ./... | xargs -tL 1 golint -set_exit_status ; fi
   - go list ./... | xargs go list -f '{{.Dir}}/*.go' | xargs -I % bash -c "misspell -error %"
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs gocyclo -over 15
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs -L 1 ineffassign
   - go list ./... | xargs go list -f '{{.Dir}}' | xargs gofmt -s -l | wc -l | xargs -I % bash -c "test % -eq 0"
   - go build ./...
